version: "3.8"
name: "broadcast-masjid"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: postgres
      PGDATABASE: postgres
      PGPASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_PORT: ${DATABASE_PORT}
      PGPORT: ${DATABASE_PORT}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - broadcast:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: ./app
    ports:
      - "${APP_PORT}:3000"
    depends_on:
      - db
    restart: unless-stopped

  # comment out if you don't want to use nginx
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  broadcast:
