CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- create table user with uuid as primary key and username as unique and password
CREATE TABLE IF NOT EXISTS "user" (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);


-- admin password: admin
INSERT INTO "user" (username, password) VALUES ('admin', '$2y$10$4vdkuf1yNPX.AVchl1He/u4nWkZD5SEh9.D7cznNfZ5ozz5AGbqC6');

-- create table "masjid"
-- "id" bigint generated by default as identity not null
-- "nama_masjid" text not null
-- "nama_ketua_dkm" text not null
-- "no_hp" text not null

CREATE TABLE IF NOT EXISTS "masjid" (
    id BIGSERIAL PRIMARY KEY,
    nama_masjid TEXT NOT NULL,
    nama_ketua_dkm TEXT NOT NULL,
    no_hp TEXT NOT NULL
);

-- create table "mubaligh"
-- "id" bigint generated by default as identity not null
-- "nama_mubaligh" text not null
-- "no_hp" text not null

CREATE TABLE IF NOT EXISTS "mubaligh" (
    id BIGSERIAL PRIMARY KEY,
    nama_mubaligh TEXT NOT NULL,
    no_hp TEXT NOT NULL
);

-- create table "pengajian"
-- "id" bigint generated by default as identity not null
-- "tanggal" date not null
-- "waktu" text not null
-- id_masjid foreign key (id_masjid) references masjid(id) on delete cascade
-- id_mubaligh foreign key (id_mubaligh) references mubaligh(id) on delete cascade

CREATE TABLE IF NOT EXISTS "pengajian" (
    id BIGSERIAL PRIMARY KEY,
    tanggal DATE NOT NULL,
    waktu TEXT NOT NULL,
    id_masjid BIGINT NOT NULL,
    id_mubaligh BIGINT NOT NULL,
    broadcasted BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (id_masjid) REFERENCES masjid(id) ON DELETE CASCADE,
    FOREIGN KEY (id_mubaligh) REFERENCES mubaligh(id) ON DELETE CASCADE
);

-- create table "jumatan"
-- "id" bigint generated by default as identity not null
-- "tanggal" timestamptz not null
-- "id_masjid" foreign key (id_masjid) references masjid(id) on delete cascade
-- "id_mubaligh" foreign key (id_mubaligh) references mubaligh(id) on delete cascade

CREATE TABLE IF NOT EXISTS "jumatan" (
    id BIGSERIAL PRIMARY KEY,
    tanggal TIMESTAMPTZ NOT NULL,
    id_masjid BIGINT NOT NULL,
    id_mubaligh BIGINT NOT NULL,
    broadcasted BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (id_masjid) REFERENCES masjid(id) ON DELETE CASCADE,
    FOREIGN KEY (id_mubaligh) REFERENCES mubaligh(id) ON DELETE CASCADE
);

-- kalo mau nambahin broadcasted di jumatan dan pengajian:
-- alter table "jumatan" add column broadcasted boolean not null default false;
-- alter table "pengajian" add column broadcasted boolean not null default false;


-- create table "template"
-- "id" bigint generated by default as identity not null
-- "nama" text not null
-- "content" text not null

create TYPE template_t as enum('pengajian_bulanan', 'pengajian_reminder', 'jumatan_reminder');

CREATE TABLE IF NOT EXISTS "template" (
    id BIGSERIAL PRIMARY KEY,
    nama_template TEXT UNIQUE NOT NULL, 
    content TEXT NOT NULL,
    type template_t NOT NULL
);

-- create table "message_logs"
-- "id" bigint generated by default as identity not null
-- "no_hp" text not null
-- "message" text not null
-- "status" text not null
-- "send_time" timestamptz not null
-- "error_reason" text

create TYPE message_status_t as enum('success', 'failed');

CREATE TABLE IF NOT EXISTS "message_logs" (
    id BIGSERIAL PRIMARY KEY,
    no_hp TEXT NOT NULL,
    message TEXT NOT NULL,
    status message_status_t NOT NULL,
    send_time TIMESTAMPTZ NOT NULL,
    error_reason TEXT
);

-- broadcast scheduling system
-- create table "broadcast_schedule"

CREATE TABLE IF NOT EXISTS "broadcast_schedule" (
    id template_t PRIMARY KEY,
    active BOOLEAN NOT NULL DEFAULT FALSE,
    force_broadcast BOOLEAN NOT NULL DEFAULT FALSE,
    h INT NOT NULL DEFAULT 0,
    jam timetz NOT NULL DEFAULT '00:00:00',
    id_template BIGINT,
    FOREIGN KEY (id_template) REFERENCES template(id) ON DELETE NO ACTION
);

INSERT INTO "broadcast_schedule" (id, active, force_broadcast, h, jam) VALUES
('pengajian_bulanan', FALSE, FALSE, 0, '00:00:00'),
('pengajian_reminder', FALSE, FALSE, 0, '00:00:00'),
('jumatan_reminder', FALSE, FALSE, 0, '00:00:00');